version: '3'
services:
  web:
    image: nginx
    ports:
    - "8000:8090"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/usr/share/nginx/html
    network_mode: "host"